# Maintainer: Kevin Jayne

repos:
  dir: ~/git
  docker-infra: github.com:WeConnect/redt-docker-infra.git

dotfiles:
  path: "{{ repo_path }}/dotfiles"
  sources:
    - { src: '.zshrc', dest: '.zshrc'}
    - { src: '.vimrc', dest: '.vimrc'}
    - { src: 'ssh.config', dest: '.ssh/config'}

cli_tools:
  - autojump
  - ctags
  - coreutils
  - curl 
  - fswatch
  - git
  - git-town
  - go
  - htop
  - jq
  - neovim
  - nmap
  - mysql
  - shellcheck
  - tree
  - watch
  - wget
  - yarn
  - zsh

cask_apps:
  - 1password
  - docker
  - intellij-idea
  - iterm2
  - java8
  - postman
  - sequel-pro
  - slack
  - spotify
  - tunnelblick
  - visual-studio-code-insiders
  - zeplin
  # - firefox
  # - google-chrome
  # - viscosity
  # - virtualbox
  # - vagrant
