# Maintainer: Kevin Jayne

repos:
  local_dir: ~/repos
  sources:
    - { src: 'git@bitbucket.org:seemywingz/dotfiles.git', dest: 'dotfiles'}
    - { src: 'https://github.com/robbyrussell/oh-my-zsh.git', dest: '../.oh-my-zsh'}
    - { src: 'https://github.com/mbadolato/iTerm2-Color-Schemes.git', dest: '../.iTerm2-Color-Schemes'}

dotfiles:
  directories:
    - ~/.ssh
    - ~/.config/nvim
  sources:
    - { src: '.zshrc', dest: '.zshrc'}
    - { src: '.bashrc', dest: '.bashrc'}
    - { src: '.vimrc', dest: '.vimrc'}
    - { src: 'ssh.config', dest: '.ssh/config'}
    - { src: 'init.vim', dest: '.config/nvim/init.vim'}

cli_tools:
  - autojump
  - awscli
  - ctags
  - coreutils
  - curl 
  - fswatch
  - git
  - htop
  - jq
  - neovim
  - nmap
  - shellcheck
  - tree
  - watch
  - wget
  - yarn
  - zsh

ubuntu:
  apt:
    keys:
      - "https://packages.microsoft.com/keys/microsoft.asc"
      - "https://packages.microsoft.com/keys/microsoft.asc"
    scripts:
      - apt_vs-code.sh
    apps:
      - spotify
      - software-properties-common 
      - apt-transport-https
      - code-insiders

mac:
  apps:
    - 1password
    - docker
    - intellij-idea
    - iterm2
    - java8
    - postman
    - sequel-pro
    - slack
    - spotify
    - tunnelblick
    - visual-studio-code-insiders
    # - zeplin
    # - charles
    # - insomnia
    # - firefox
    # - google-chrome
    # - viscosity
    # - virtualbox
    # - vagrant
