# Maintainer: Kevin Jayne

repos:
  local_dir: ~/git
  sources:
    - { src: 'git@github.com:WeConnect/redt-docker-infra.git', dest: 'redt-docker-infra'}
    - { src: 'git@github.com:WeConnect/redt-onelogin-aws-saml', dest: 'redt-onelogin-aws-saml'}

dotfiles:
  sources:
    - { src: '.zshrc', dest: '.zshrc'}
    - { src: '.bashrc', dest: '.bashrc'}
    - { src: '.vimrc', dest: '.vimrc'}
    - { src: '.vimrc', dest: '.vimrc'}
    - { src: 'ssh.config', dest: '.ssh/config'}
    - { src: 'aws.credentials', dest: '.aws/credentials'}
    - { src: 'gradle.properties', dest: '.gradle/gradle.properties'}

cli_tools:
  - autojump
  - awscli
  - ctags
  - coreutils
  - curl 
  - fswatch
  - git
  - git-town
  - go
  - htop
  - jq
  - neovim
  - nmap
  - mysql
  - shellcheck
  - tree
  - watch
  - wget
  - yarn
  - zsh

cask_apps:
  - 1password
  - docker
  - intellij-idea
  - iterm2
  - java8
  - postman
  - sequel-pro
  - slack
  - spotify
  - tunnelblick
  - visual-studio-code-insiders
  # - zeplin
  # - charles
  # - insomnia
  # - firefox
  # - google-chrome
  # - viscosity
  # - virtualbox
  # - vagrant
