# Maintainer: Kevin Jayne

repos:
  local_dir: ~/git
  sources:
    - { src: 'git@github.com:WeConnect/redt-docker-infra.git', dest: 'redt-docker-infra'}
    - { src: 'git@github.com:WeConnect/redt-onelogin-aws-saml', dest: 'redt-onelogin-aws-saml'}
    - { src: 'https://github.com/robbyrussell/oh-my-zsh.git', dest: '../.oh-my-zsh'}
    - { src: 'https://github.com/mbadolato/iTerm2-Color-Schemes.git', dest: '../.iTerm2-Color-Schemes'}

docker:
  login:
    registry: https://fieldlens-docker-dev-local.jfrog.io
  images:
    - { src: 'redt-onelogin-aws-saml', img: 'onelogin-aws-saml'}

dotfiles:
  directories:
    - ~/.aws
    - ~/.ssh
    - ~/.gradle
    - ~/.config/nvim
  sources:
    - { src: '.zshrc', dest: '.zshrc'}
    - { src: '.bashrc', dest: '.bashrc'}
    - { src: '.vimrc', dest: '.vimrc'}
    - { src: '.vimrc', dest: '.vimrc'}
    - { src: 'ssh.config', dest: '.ssh/config'}
    - { src: 'aws.credentials', dest: '.aws/credentials'}
    - { src: 'init.vim', dest: '.config/nvim/init.vim'}
    - { src: 'gradle.properties', dest: '.gradle/gradle.properties'}

cli_tools:
  - autojump
  - awscli
  - ctags
  - coreutils
  - curl 
  - fswatch
  - git
  - git-town
  - go
  - htop
  - jq
  - neovim
  - nmap
  - mysql
  - shellcheck
  - tree
  - watch
  - wget
  - yarn
  - zsh

cask_apps:
  - 1password
  - docker
  - intellij-idea
  - iterm2
  - java8
  - postman
  - sequel-pro
  - slack
  - spotify
  - tunnelblick
  - visual-studio-code-insiders
  # - zeplin
  # - charles
  # - insomnia
  # - firefox
  # - google-chrome
  # - viscosity
  # - virtualbox
  # - vagrant
