# vim:ft=ansible
- name: Create Config Directories
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ dotfiles.directories }}"

- name: Copy Dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
  with_items:
    - "{{ dotfiles.sources }}"