# vim:ft=ansible
- name: Create Config Directories
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ dotfiles.config.directories }}"

- name: Link Shared Dotfiles
  file:
    src: "{{ repos.local_dir }}/dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
    state: link
  with_items:
    - "{{ dotfiles.sources.shared }}"

- name: Link Mac Dotfiles
  file:
    src: "{{ repos.local_dir }}/dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
    state: link
  with_items:
    - "{{ dotfiles.sources.mac }}"
  when: ansible_distribution == "MacOSX"

- name: Link Ubuntu Dotfiles
  file:
    src: "{{ repos.local_dir }}/dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
    state: link
  with_items:
    - "{{ dotfiles.sources.ubuntu }}"
  when: ansible_distribution == "Ubuntu"
