# vim:ft=ansible

# - name: Install Caskroom Apps
#   homebrew_cask:
#     name: "{{item}}"
#     state: "present"
#   with_items:
#     - "{{ mac.apps }}"
#   ignore_errors: yes
#   when: ansible_distribution == "MacOSX"

- name: Update Homebrew
  homebrew:
    update_homebrew: "yes"
  when: ansible_distribution == "MacOSX"

- name: Installs Caskroom Apps Workaround
  shell: "brew install {{ item }} --cask"
  with_items:
    - "{{ mac.apps }}"
  ignore_errors: yes
  when: ansible_distribution == "MacOSX"

- name: Accept Apt Server GPG Keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ ubuntu.server.gpg }}"
  when: ansible_distribution == "Ubuntu" and ubuntu.server.gpg is defined

- name: Add Apt Server PPAs
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ ubuntu.server.ppa }}"
  when: ansible_distribution == "Ubuntu" and ubuntu.server.ppa is defined

- name: Install Server Applications via Apt
  become: true
  apt:
    pkg: "{{ ubuntu.server.packages }}"
    state: present
    update_cache: "yes"
  when: ansible_distribution == "Ubuntu"

- name: Accept Apt Desktop GPG Keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ ubuntu.desktop.gpg }}"
  when: ansible_distribution == "Ubuntu" and 'remote' not in group_names

- name: Add Apt Desktop PPAs
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ ubuntu.desktop.ppa }}"
  when: ansible_distribution == "Ubuntu" and 'remote' not in group_names

- name: Install Desktop Applications via Apt
  become: true
  apt:
    pkg: "{{ ubuntu.desktop.packages }}"
    state: present
    update_cache: "yes"
  when: ansible_distribution == "Ubuntu" and 'remote' not in group_names

- name: Install Applications via Snap
  become: true
  command: snap install "{{ item }}"
  with_items:
    - "{{ ubuntu.desktop.snap }}"
  when: ansible_distribution == "Ubuntu" and 'remote' not in group_names
