# vim:ft=ansible

- name: Install Brew Caskroom and Versions
  command: "{{ item }}"
  with_items:
    - brew install caskroom/cask/brew-cask
    - brew tap caskroom/versions
  when: ansible_distribution == "MacOSX"

- name: Install Caskroom Apps
  homebrew_cask:
    name: "{{item}}"
    state: "present"
  with_items:
    - "{{ mac.apps }}"
  ignore_errors: yes
  when: ansible_distribution == "MacOSX"

- name: Accept Apt GPG Keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ ubuntu.apt.gpg }}"
  when: ansible_distribution == "Ubuntu"

- name: Add Apt PPAs
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ ubuntu.apt.ppa }}"
  when: ansible_distribution == "Ubuntu"


- name: Install Applications via Apt
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: "yes"
  with_items:
    - "{{ ubuntu.apt.apps }}"
  when: ansible_distribution == "Ubuntu"

- name: Install Applications via snap
  become: true
  command: snap install "{{ item }}"
  with_items:
    - "{{ ubuntu.snap.apps }}"
  when: ansible_distribution == "Ubuntu"