
- name: Install Caskroom
  command: brew install caskroom/cask/brew-cask
    
- name: Install Caskroom Apps
  homebrew_cask:
    name: "{{item}}"
    state: "present"
  with_items:
    - "{{ cask_apps }}"
  ignore_errors: yes
