# EMN DevOps initializer

- name: Provision RedTech Mac for Local Development
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - { role: cli, tags: [ 'init', 'cli' ]  }
    - { role: apps, tags: [ 'init', 'apps' ]  }
    - { role: repos, tags: [ 'init', 'repos' ]  }
    - { role: dotfiles, tags: [ 'init', 'dotfiles' ]  }