# vim:ft=ansible

- name: Install CLI Tools via Homebrew
  homebrew:
    pkg: "{{ item }}"
    state: present
    update_homebrew: "yes"
  with_items:
    - "{{ cli_tools }}"
  when: ansible_distribution == "MacOSX"

- name: Install CLI Tools via Apt
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: "yes"
  with_items:
    - "{{ cli_tools }}"
  when: ansible_distribution == "Ubuntu"
