# vim:ft=ansible

- name: Tap OpenJDK
  homebrew_tap:
    name: "{{openJDK.tap}}"

- name: Install CLI Tools via Homebrew
  homebrew:
    pkg: "{{ item }}"
    state: present
    update_homebrew: "yes"
  with_items:
    - "{{ cli_tools }}"
