# vim:ft=ansible

- name: Install CLI Tools via Homebrew
  homebrew:
    pkg: "{{ cli_tools }}"
    state: present
    update_homebrew: "yes"
  when: ansible_distribution == "MacOSX"

- name: Install CLI Tools via Apt
  become: true
  apt:
    pkg: "{{ cli_tools }}"
    state: present
    update_cache: "yes"
  # with_items:
  #   - "{{ cli_tools }}"
  when: ansible_distribution == "Ubuntu"
